name: Release

on:
  push:
    branches:
    - release

jobs:
  terraform-release:
    if: github.ref == 'refs/heads/release'
    name: 'terraform:release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        branches: |
          [
            'release'
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
